services:
  cinemactrl-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  cinemactrl-backend:
    build:
      context: ./backend
      tags:
        - cinemactrl/backend:latest
    environment:
      CINEMACTRL_DB_HOST: cinemactrl-postgres
      CINEMACTRL_DB_PASSWORD: password
      CINEMACTRL_DB_USER: user
      CINEMACTRL_DB_DATABASE: appdb
      CINEMACTRL_DB_PORT: 5432
    ports:
      - "3000:80"
    depends_on:
      - cinemactrl-postgres
      - cinemactrl-booking
      - cinemactrl-user
      - cinemactrl-logging
  cinemactrl-frontend:
    build:
      context: ./frontend
      tags:
        - cinemactrl/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - cinemactrl-backend
  cinemactrl-booking:
    environment:
      CINEMACTRL_DB_HOST: cinemactrl-postgres
      CINEMACTRL_DB_PASSWORD: password
      CINEMACTRL_DB_USER: user
      CINEMACTRL_DB_DATABASE: appdb
      CINEMACTRL_DB_PORT: 5432
    build:
      context: ./backend
      args:
        - BUILT_SERVICE=booking-service
      tags:
        - cinemactrl/backend-booking:latest
  cinemactrl-user:
    environment:
      CINEMACTRL_DB_HOST: cinemactrl-postgres
      CINEMACTRL_DB_PASSWORD: password
      CINEMACTRL_DB_USER: user
      CINEMACTRL_DB_DATABASE: appdb
      CINEMACTRL_DB_PORT: 5432
    build:
      context: ./backend
      args:
        - BUILT_SERVICE=user-service
      tags:
        - cinemactrl/backend-user:latest
  cinemactrl-logging:
    environment:
      CINEMACTRL_DB_HOST: cinemactrl-postgres
      CINEMACTRL_DB_PASSWORD: password
      CINEMACTRL_DB_USER: user
      CINEMACTRL_DB_DATABASE: appdb
      CINEMACTRL_DB_PORT: 5432
    build:
      context: ./backend
      args:
        - BUILT_SERVICE=logging-service
      tags:
        - cinemactrl/backend-logging:latest
volumes:
  postgres_data:
    driver: local
