services:
  cinemactrl-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  cinemactrl-backend:
    build:
      context: ./backend
      tags:
        - cinemactrl/backend:latest
    environment:
      CINEMACTRL_DB_HOST: cinemactrl-postgres
      CINEMACTRL_DB_PASSWORD: password
      CINEMACTRL_DB_USER: user
      CINEMACTRL_DB_DATABASE: appdb
      CINEMACTRL_DB_PORT: 5432
      BOOKING_SERVICE_URL: http://cinemactrl-booking
      USER_SERVICE_URL: http://cinemactrl-user
      LOGGING_SERVICE_URL: http://cinemactrl-logging
    ports:
      - "3000:80"
    depends_on:
      - cinemactrl-postgres
      - cinemactrl-booking
      - cinemactrl-user
      - cinemactrl-logging
  cinemactrl-frontend:
    depends_on:
      - cinemactrl-backend
    build:
      context: ./frontend
      tags:
        - cinemactrl/frontend:latest
    ports:
      - "80:80"
  cinemactrl-booking:
    depends_on:
      - cinemactrl-postgres
    environment:
      CINEMACTRL_DB_HOST: cinemactrl-postgres
      CINEMACTRL_DB_PASSWORD: password
      CINEMACTRL_DB_USER: user
      CINEMACTRL_DB_DATABASE: appdb
      CINEMACTRL_DB_PORT: 5432
    build:
      context: ./backend
      args:
        - BUILT_SERVICE=booking-service
      tags:
        - cinemactrl/backend-booking:latest
  cinemactrl-user:
    depends_on:
      - cinemactrl-postgres
    environment:
      CINEMACTRL_DB_HOST: cinemactrl-postgres
      CINEMACTRL_DB_PASSWORD: password
      CINEMACTRL_DB_USER: user
      CINEMACTRL_DB_DATABASE: appdb
      CINEMACTRL_DB_PORT: 5432
    build:
      context: ./backend
      args:
        - BUILT_SERVICE=user-service
      tags:
        - cinemactrl/backend-user:latest
  cinemactrl-logging:
    depends_on:
      - cinemactrl-postgres
    environment:
      CINEMACTRL_DB_HOST: cinemactrl-postgres
      CINEMACTRL_DB_PASSWORD: password
      CINEMACTRL_DB_USER: user
      CINEMACTRL_DB_DATABASE: appdb
      CINEMACTRL_DB_PORT: 5432
    build:
      context: ./backend
      args:
        - BUILT_SERVICE=logging-service
      tags:
        - cinemactrl/backend-logging:latest
  cinemactrl-seeder:
    depends_on:
      - cinemactrl-postgres
    build:
      context: ./seeds
      tags:
        - cinemactrl/backend-seeder:latest
    environment:
      CINEMACTRL_DB_HOST: cinemactrl-postgres
      CINEMACTRL_DB_PASSWORD: password
      CINEMACTRL_DB_USER: user
      CINEMACTRL_DB_DATABASE: appdb
      CINEMACTRL_DB_PORT: 5432

volumes:
  postgres_data:
    driver: local
