FROM node:lts-alpine AS builder

ARG BUILT_SERVICE=backend

WORKDIR /app

COPY . .

RUN npm i -g bun

RUN bun i

RUN bun run build ${BUILT_SERVICE}

FROM node:lts-alpine AS runner

ARG BUILT_SERVICE=backend

WORKDIR /app

RUN npm i -g bun

COPY --from=builder /app/dist/apps/${BUILT_SERVICE} ./dist
COPY --from=builder /app/package.json .
COPY --from=builder /app/bun.lock .
COPY --from=builder /app/package-lock.json .

RUN bun i

ENV PORT=80

EXPOSE 80

CMD ["node", "./dist/main.js"]
